server:
  port: 8081

spring:
  application:
    name: customer-service
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/customer_db}
    username: ${DB_USER:cmp_user}
    password: ${DB_PASSWORD:cmp_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

